name: CI - Test environment

on:
  push:
    branches: [ "main" ]
    paths:
    - "**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies n run tests
        run: npm install
             npm run test:coverage