name: CI - Test environment

on:
  push:
    branches: [ "master" ]
    paths:
    - "**"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./Backend

      - name: test execution
        run: npm run testcoverage
        working-directory: ./Backend

      - name: check results
        run: npm run testcoverage -- --ci

      - name: build docker
        run: docker build -t myapp .
      
      - name: run docker
        run: docker run --rm -v ${{ github.workspace }}:/app myapp npm run testcoverage